#!/bin/bash -e

# Copyright (c) 2014 The CoreOS Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# We want to grab the GROUP variable
[ -e /usr/share/flatcar/update.conf ] && source /usr/share/flatcar/update.conf
[ -e /etc/flatcar/update.conf ] && source /etc/flatcar/update.conf

source /usr/lib/os-release

mkdir -p /run/flatcar
echo -e "\e[${ANSI_COLOR}m${NAME}\e[39m ${GROUP} (${VERSION})" > /run/flatcar/motd

if [[ -d "/etc/motd.d" ]]; then
	cat /etc/motd.d/*.conf 2>/dev/null >> /run/flatcar/motd || true
fi
